package consultorio.mapper;

import consultorio.domain.paciente.Paciente;
import consultorio.dto.request.paciente.PacienteRequest;
import consultorio.dto.response.paciente.PacienteResponse;
import org.springframework.stereotype.Component;

@Component
public class PacienteMapper {

    public Paciente toEntity(PacienteRequest request) {
        return Paciente.builder()
                .prontuario(request.getProntuario())
                .nome(request.getNome())
                .telefone(request.getTelefone())
                .rg(request.getRg())
                .orgaoExpedidor(request.getOrgaoExpedidor())
                .cpf(request.getCpf())
                .dataNascimento(request.getDataNascimento())
                .sexo(request.getSexo())
                .naturalidade(request.getNaturalidade())
                .nacionalidade(request.getNacionalidade())
                .estadoCivil(request.getEstadoCivil())
                .profissao(request.getProfissao())
                .enderecoResidencial(request.getEnderecoResidencial())
                .indicadoPor(request.getIndicadoPor())
                .convenio(request.getConvenio())
                .numeroInscricao(request.getNumeroInscricao())
                .responsavelNome(request.getResponsavelNome())
                .responsavelRg(request.getResponsavelRg())
                .responsavelOrgaoExpedidor(request.getResponsavelOrgaoExpedidor())
                .responsavelCpf(request.getResponsavelCpf())
                .responsavelEstadoCivil(request.getResponsavelEstadoCivil())
                .responsavelConjuge(request.getResponsavelConjuge())
                .responsavelRgConjuge(request.getResponsavelRgConjuge())
                .responsavelOrgaoExpedidorConjuge(request.getResponsavelOrgaoExpedidorConjuge())
                .responsavelCpfConjuge(request.getResponsavelCpfConjuge())
                .febreReumatica(request.getFebreReumatica())
                .hepatite(request.getHepatite())
                .diabetes(request.getDiabetes())
                .hipertensaoArterial(request.getHipertensaoArterial())
                .portadorHiv(request.getPortadorHiv())
                .alteracaoCoagulacao(request.getAlteracaoCoagulacao())
                .reacoesAlergicas(request.getReacoesAlergicas())
                .doencasSystemicas(request.getDoencasSystemicas())
                .tratamentosMedicosAnteriores(request.getTratamentosMedicosAnteriores())
                .internacaoRecente(request.getInternacaoRecente())
                .utilizandoMedicacao(request.getUtilizandoMedicacao())
                .medicacaoNome(request.getMedicacaoNome())
                .medicacaoQuantidade(request.getMedicacaoQuantidade())
                .medicacaoTempo(request.getMedicacaoTempo())
                .bebidasAlcoolicas(request.getBebidasAlcoolicas())
                .problemasCardiacos(request.getProblemasCardiacos())
                .problemasRenais(request.getProblemasRenais())
                .problemasGastricos(request.getProblemasGastricos())
                .problemasRespiratorios(request.getProblemasRespiratorios())
                .problemasAlergicos(request.getProblemasAlergicos())
                .problemasArticulares(request.getProblemasArticulares())
                .queixaPrincipal(request.getQueixaPrincipal())
                .sofreDoenca(request.getSofreDoenca())
                .doencaQual(request.getDoencaQual())
                .emTratamentoMedico(request.getEmTratamentoMedico())
                .gravidez(request.getGravidez())
                .fazendoUsoMedicacao(request.getFazendoUsoMedicacao())
                .medicacaoQual(request.getMedicacaoQual())
                .medicoAssistente(request.getMedicoAssistente())
                .medicoTelefone(request.getMedicoTelefone())
                .temAlergia(request.getTemAlergia())
                .alergiaQual(request.getAlergiaQual())
                .foiOperado(request.getFoiOperado())
                .operacaoQual(request.getOperacaoQual())
                .problemasCicatrizacao(request.getProblemasCicatrizacao())
                .problemasAnestesia(request.getProblemasAnestesia())
                .problemasHemorragia(request.getProblemasHemorragia())
                .habitos(request.getHabitos())
                .antecedentesFamiliares(request.getAntecedentesFamiliares())
                .lingua(request.getLingua())
                .mucosa(request.getMucosa())
                .palato(request.getPalato())
                .labios(request.getLabios())
                .gengivas(request.getGengivas())
                .nariz(request.getNariz())
                .face(request.getFace())
                .ganglios(request.getGanglios())
                .glandulasSalivares(request.getGlandulasSalivares())
                .alteracaoOclusao(request.getAlteracaoOclusao())
                .alteracaoOclusaoTipo(request.getAlteracaoOclusaoTipo())
                .protese(request.getProtese())
                .proteseTipo(request.getProteseTipo())
                .outrasObservacoes(request.getOutrasObservacoes())
                .build();
    }

    public PacienteResponse toResponse(Paciente paciente) {
        return PacienteResponse.builder()
                .id(paciente.getId())
                .prontuario(paciente.getProntuario())
                .nome(paciente.getNome())
                .telefone(paciente.getTelefone())
                .rg(paciente.getRg())
                .orgaoExpedidor(paciente.getOrgaoExpedidor())
                .cpf(paciente.getCpf())
                .dataNascimento(paciente.getDataNascimento())
                .sexo(paciente.getSexo())
                .naturalidade(paciente.getNaturalidade())
                .nacionalidade(paciente.getNacionalidade())
                .estadoCivil(paciente.getEstadoCivil())
                .profissao(paciente.getProfissao())
                .enderecoResidencial(paciente.getEnderecoResidencial())
                .indicadoPor(paciente.getIndicadoPor())
                .convenio(paciente.getConvenio())
                .numeroInscricao(paciente.getNumeroInscricao())
                .responsavelNome(paciente.getResponsavelNome())
                .responsavelRg(paciente.getResponsavelRg())
                .responsavelOrgaoExpedidor(paciente.getResponsavelOrgaoExpedidor())
                .responsavelCpf(paciente.getResponsavelCpf())
                .responsavelEstadoCivil(paciente.getResponsavelEstadoCivil())
                .responsavelConjuge(paciente.getResponsavelConjuge())
                .responsavelRgConjuge(paciente.getResponsavelRgConjuge())
                .responsavelOrgaoExpedidorConjuge(paciente.getResponsavelOrgaoExpedidorConjuge())
                .responsavelCpfConjuge(paciente.getResponsavelCpfConjuge())
                .febreReumatica(paciente.getFebreReumatica())
                .hepatite(paciente.getHepatite())
                .diabetes(paciente.getDiabetes())
                .hipertensaoArterial(paciente.getHipertensaoArterial())
                .portadorHiv(paciente.getPortadorHiv())
                .alteracaoCoagulacao(paciente.getAlteracaoCoagulacao())
                .reacoesAlergicas(paciente.getReacoesAlergicas())
                .doencasSystemicas(paciente.getDoencasSystemicas())
                .tratamentosMedicosAnteriores(paciente.getTratamentosMedicosAnteriores())
                .internacaoRecente(paciente.getInternacaoRecente())
                .utilizandoMedicacao(paciente.getUtilizandoMedicacao())
                .medicacaoNome(paciente.getMedicacaoNome())
                .medicacaoQuantidade(paciente.getMedicacaoQuantidade())
                .medicacaoTempo(paciente.getMedicacaoTempo())
                .bebidasAlcoolicas(paciente.getBebidasAlcoolicas())
                .problemasCardiacos(paciente.getProblemasCardiacos())
                .problemasRenais(paciente.getProblemasRenais())
                .problemasGastricos(paciente.getProblemasGastricos())
                .problemasRespiratorios(paciente.getProblemasRespiratorios())
                .problemasAlergicos(paciente.getProblemasAlergicos())
                .problemasArticulares(paciente.getProblemasArticulares())
                .queixaPrincipal(paciente.getQueixaPrincipal())
                .sofreDoenca(paciente.getSofreDoenca())
                .doencaQual(paciente.getDoencaQual())
                .emTratamentoMedico(paciente.getEmTratamentoMedico())
                .gravidez(paciente.getGravidez())
                .fazendoUsoMedicacao(paciente.getFazendoUsoMedicacao())
                .medicacaoQual(paciente.getMedicacaoQual())
                .medicoAssistente(paciente.getMedicoAssistente())
                .medicoTelefone(paciente.getMedicoTelefone())
                .temAlergia(paciente.getTemAlergia())
                .alergiaQual(paciente.getAlergiaQual())
                .foiOperado(paciente.getFoiOperado())
                .operacaoQual(paciente.getOperacaoQual())
                .problemasCicatrizacao(paciente.getProblemasCicatrizacao())
                .problemasAnestesia(paciente.getProblemasAnestesia())
                .problemasHemorragia(paciente.getProblemasHemorragia())
                .habitos(paciente.getHabitos())
                .antecedentesFamiliares(paciente.getAntecedentesFamiliares())
                .lingua(paciente.getLingua())
                .mucosa(paciente.getMucosa())
                .palato(paciente.getPalato())
                .labios(paciente.getLabios())
                .gengivas(paciente.getGengivas())
                .nariz(paciente.getNariz())
                .face(paciente.getFace())
                .ganglios(paciente.getGanglios())
                .glandulasSalivares(paciente.getGlandulasSalivares())
                .alteracaoOclusao(paciente.getAlteracaoOclusao())
                .alteracaoOclusaoTipo(paciente.getAlteracaoOclusaoTipo())
                .protese(paciente.getProtese())
                .proteseTipo(paciente.getProteseTipo())
                .outrasObservacoes(paciente.getOutrasObservacoes())
                .criadoEm(paciente.getCriadoEm())
                .atualizadoEm(paciente.getAtualizadoEm())
                .build();
    }

    public void updateEntity(Paciente paciente, PacienteRequest request) {
        paciente.setProntuario(request.getProntuario());
        paciente.setNome(request.getNome());
        paciente.setTelefone(request.getTelefone());
        paciente.setRg(request.getRg());
        paciente.setOrgaoExpedidor(request.getOrgaoExpedidor());
        paciente.setCpf(request.getCpf());
        paciente.setDataNascimento(request.getDataNascimento());
        paciente.setSexo(request.getSexo());
        paciente.setNaturalidade(request.getNaturalidade());
        paciente.setNacionalidade(request.getNacionalidade());
        paciente.setEstadoCivil(request.getEstadoCivil());
        paciente.setProfissao(request.getProfissao());
        paciente.setEnderecoResidencial(request.getEnderecoResidencial());
        paciente.setIndicadoPor(request.getIndicadoPor());
        paciente.setConvenio(request.getConvenio());
        paciente.setNumeroInscricao(request.getNumeroInscricao());
        paciente.setResponsavelNome(request.getResponsavelNome());
        paciente.setResponsavelRg(request.getResponsavelRg());
        paciente.setResponsavelOrgaoExpedidor(request.getResponsavelOrgaoExpedidor());
        paciente.setResponsavelCpf(request.getResponsavelCpf());
        paciente.setResponsavelEstadoCivil(request.getResponsavelEstadoCivil());
        paciente.setResponsavelConjuge(request.getResponsavelConjuge());
        paciente.setResponsavelRgConjuge(request.getResponsavelRgConjuge());
        paciente.setResponsavelOrgaoExpedidorConjuge(request.getResponsavelOrgaoExpedidorConjuge());
        paciente.setResponsavelCpfConjuge(request.getResponsavelCpfConjuge());
        paciente.setFebreReumatica(request.getFebreReumatica());
        paciente.setHepatite(request.getHepatite());
        paciente.setDiabetes(request.getDiabetes());
        paciente.setHipertensaoArterial(request.getHipertensaoArterial());
        paciente.setPortadorHiv(request.getPortadorHiv());
        paciente.setAlteracaoCoagulacao(request.getAlteracaoCoagulacao());
        paciente.setReacoesAlergicas(request.getReacoesAlergicas());
        paciente.setDoencasSystemicas(request.getDoencasSystemicas());
        paciente.setTratamentosMedicosAnteriores(request.getTratamentosMedicosAnteriores());
        paciente.setInternacaoRecente(request.getInternacaoRecente());
        paciente.setUtilizandoMedicacao(request.getUtilizandoMedicacao());
        paciente.setMedicacaoNome(request.getMedicacaoNome());
        paciente.setMedicacaoQuantidade(request.getMedicacaoQuantidade());
        paciente.setMedicacaoTempo(request.getMedicacaoTempo());
        paciente.setBebidasAlcoolicas(request.getBebidasAlcoolicas());
        paciente.setProblemasCardiacos(request.getProblemasCardiacos());
        paciente.setProblemasRenais(request.getProblemasRenais());
        paciente.setProblemasGastricos(request.getProblemasGastricos());
        paciente.setProblemasRespiratorios(request.getProblemasRespiratorios());
        paciente.setProblemasAlergicos(request.getProblemasAlergicos());
        paciente.setProblemasArticulares(request.getProblemasArticulares());
        paciente.setQueixaPrincipal(request.getQueixaPrincipal());
        paciente.setSofreDoenca(request.getSofreDoenca());
        paciente.setDoencaQual(request.getDoencaQual());
        paciente.setEmTratamentoMedico(request.getEmTratamentoMedico());
        paciente.setGravidez(request.getGravidez());
        paciente.setFazendoUsoMedicacao(request.getFazendoUsoMedicacao());
        paciente.setMedicacaoQual(request.getMedicacaoQual());
        paciente.setMedicoAssistente(request.getMedicoAssistente());
        paciente.setMedicoTelefone(request.getMedicoTelefone());
        paciente.setTemAlergia(request.getTemAlergia());
        paciente.setAlergiaQual(request.getAlergiaQual());
        paciente.setFoiOperado(request.getFoiOperado());
        paciente.setOperacaoQual(request.getOperacaoQual());
        paciente.setProblemasCicatrizacao(request.getProblemasCicatrizacao());
        paciente.setProblemasAnestesia(request.getProblemasAnestesia());
        paciente.setProblemasHemorragia(request.getProblemasHemorragia());
        paciente.setHabitos(request.getHabitos());
        paciente.setAntecedentesFamiliares(request.getAntecedentesFamiliares());
        paciente.setLingua(request.getLingua());
        paciente.setMucosa(request.getMucosa());
        paciente.setPalato(request.getPalato());
        paciente.setLabios(request.getLabios());
        paciente.setGengivas(request.getGengivas());
        paciente.setNariz(request.getNariz());
        paciente.setFace(request.getFace());
        paciente.setGanglios(request.getGanglios());
        paciente.setGlandulasSalivares(request.getGlandulasSalivares());
        paciente.setAlteracaoOclusao(request.getAlteracaoOclusao());
        paciente.setAlteracaoOclusaoTipo(request.getAlteracaoOclusaoTipo());
        paciente.setProtese(request.getProtese());
        paciente.setProteseTipo(request.getProteseTipo());
        paciente.setOutrasObservacoes(request.getOutrasObservacoes());
    }
}
